# Generated by Django 4.2.11 on 2024-04-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('time', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BusStopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop_name', models.CharField(max_length=225)),
                ('latitude', models.CharField(max_length=125)),
                ('longitude', models.CharField(max_length=125)),
                ('buss', models.ManyToManyField(to='bus_ip.busmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
