# Generated by Django 4.2.6 on 2023-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.JSONField(default={'locations': []}),
        ),
    ]
