# Generated by Django 4.2.6 on 2023-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_route_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.JSONField(default="{'locations':[]}"),
        ),
    ]
