# Generated by Django 4.2.6 on 2023-11-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_route_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.JSONField(),
        ),
    ]
